name: catalogo_online
description: Aplicativo Flutter MVVM que consome https://fakestoreapi.com/products
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
